/*
Copyright (c) 2012-2013 Kevin Scott All rights  reserved. Permission is hereby granted, free of charge, to any person obtaining a copy of 
 this software and associated documentation files (the "Software"), to deal in 
 the Software without restriction, including without limitation the rights to 
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
 so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ 
/** data Object talks to DB **/
package org.javaWebGen.data.dao;

import javax.annotation.Generated;
/******************************************************************************
* WARNING this class is generated by GenerateDAOFactory v0_13 based on Database schema     
* This class should not be modified, but may be extended.
*  This class will be regenerated if the database schema is changed. 
* @author Kevin Scott                                                        
*******************************************************************************/
@Generated(value = { "org.javaWebGen.generator.GenerateDAOFactory" })
public  class DaoFactory{ 
//begin private Vars
private PublisherDAO publisherDao=null;
private AuthorDAO authorDao=null;
private BookDAO bookDao=null;

//begin getters and setters
/********************************************
*DataBase Access Object
*@return dao set by Spring Context
**********************************************/
public PublisherDAO getPublisherDao(){
    return publisherDao;
}
/********************************************
*DataBase Access Object
*@Param dao set by Spring Context
***********************************************/
public void setPublisherDao(PublisherDAO PublisherDao){
    this.publisherDao = PublisherDao;
}
/********************************************
*DataBase Access Object
*@return dao set by Spring Context
**********************************************/
public AuthorDAO getAuthorDao(){
    return authorDao;
}
/********************************************
*DataBase Access Object
*@Param dao set by Spring Context
***********************************************/
public void setAuthorDao(AuthorDAO AuthorDao){
    this.authorDao = AuthorDao;
}
/********************************************
*DataBase Access Object
*@return dao set by Spring Context
**********************************************/
public BookDAO getBookDao(){
    return bookDao;
}
/********************************************
*DataBase Access Object
*@Param dao set by Spring Context
***********************************************/
public void setBookDao(BookDAO BookDao){
    this.bookDao = BookDao;
}

}
