<%/****************************************************************************
* WARNING this JSP is generated by GenerateView 4_17 based on Database schema
* This is only a place holder.  It will NOT be overwritten.  Customize as needed 
*******************************************************************************/%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@attribute name="meta" fragment="true" %>
<%@attribute name="style" fragment="true" %>
<%@attribute name="script" fragment="true" %>
<%@attribute name="initJSFunction" fragment="true" %>
<%@attribute name="bodyScript" fragment="true" %>
<%@attribute name="title" fragment="true" %>
<html lang="en">
	<head>
	  <meta name="copyright" content="Copyright 2017">
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
	   <jsp:invoke fragment='meta'/>
	    <meta name='author' content='' >
	    <link rel='shortcut icon' href='<c:url value="/static/favicon.ico"/>'>
	    <!-- <meta name='viewport' content='width=device-width, initial-scale=1'>    -->
<!-- Bootstrap -->
	<link href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css'	rel='stylesheet'>
  <link href='<c:url value="/static/css/bootstrap-datepicker.min.css"/>'	rel='stylesheet'>  <link href='<c:url value="/static/css/bootstrap-timepicker.min.css"/>' rel='stylesheet'>
	<link href='<c:url value="/static/css/webApp.css"/>' rel='stylesheet'>
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
 	  <script src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'></script>
	  <script src='https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js'></script>
	<![endif]-->
	<script>
  	function init(){
		<jsp:invoke fragment='initJSFunction'/>
	}
	</script>
 	 <script><jsp:invoke fragment='script' /></script>
  	<title><jsp:invoke fragment='title'/></title> 
   	  </head>
    	  
    	  <body onLoad="init()">
    	 	<!--begin menu-->
    	    <div class='navbar navbar-inverse navbar-fixed-top' role="navigation">
    	      <div class='container'>
    	        <div class='navbar-header'>
    	          <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
    	            <span class='sr-only'>Toggle navigation</span>
   	            <span class='icon-bar'></span>
    	          </button>
  	          <a class='navbar-brand active' href='/admin/index.jsp'>Admin</a>
 	        </div>
  	        <div class='collapse navbar-collapse'>
	          <ul class='nav navbar-nav'>
            <li> </li>
 </ul>
 </div><!--/.nav-collapse -->
 </div>
</div>
<!--end menu-->  
<div class='container'>
<div class='col-m'>	
	<div class='webApp'><jsp:doBody/></div>	 
</div>	
</div>
<footer class='navbar navbar-fixed-bottom'><div class="container">

<jsp:include page='/inc/footer.jsp' flush='false'/>
</div></footer>
</div><!-- /.container --> 
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js'></script>
<script src='<c:url value="/static/js/bootstrap-datepicker.min.js"/>'></script><script src='<c:url value="/static/js/bootstrap-timepicker.min.js"/>'></script><script>
<jsp:invoke fragment='bodyScript'/> 
</script>
</body>
<!--end base template 4_17-->
</html>