/*
Copyright (c) 2012-2017 Kevin Scott All rights  reserved.
 Permission is hereby granted, free of charge, to any person obtaining a copy of 
 this software and associated documentation files (the "Software"), to deal in 
 the Software without restriction, including without limitation the rights to 
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
 so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ 
/* data Acees Object talks to DB */
package org.javaWebGen.controller;
import javax.servlet.http.*;
import java.util.*;
import org.javaWebGen.data.bean.*;
import org.javaWebGen.WebController;
import org.javaWebGen.util.HtmlUtil;
import org.javaWebGen.util.StringUtil;
import org.javaWebGen.exception.*;
import org.javaWebGen.model.*;
import org.javaWebGen.config.ConfigConst;
import org.javaWebGen.config.WebConst;
import org.javaWebGen.JavaWebGenContext;
import org.javaWebGen.webform.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
/******************************************************************************
* WARNING this class is generated by GenerateSpringController v2_022 based on Database schema     
* This class should not be modified!
It will be regenerated by the code generator * when the database schema is modified
* If you need to change the this code you should override main class with what you do not need.
*******************************************************************************/
public abstract class AuthorActionImpl extends WebController { 
@SuppressWarnings("unused")
private static final Logger log=LoggerFactory.getLogger(AuthorActionImpl.class);//begin private Vars
	
/** model for this object **/;
	private AuthorModel model= null;

//begin update(store)

//begin delete(store)

	/***************************************************
	*Warning Generated method updates the database with a Databean 
	*@param bean data bound JavaBean
	*@see org.javaWebGen.data.DataBean
	*
	******************************************************/
	protected void delete(Author bean) throws WebAppException{
		getModel().remove(bean);
	} //end delete

//begin listAll)
//${javaWebGen.listAll}
//begin getDataBean
	/************************************
	*fills in a databean based on data in a request
	************************************/
	public static Author getDataBean(HttpServletRequest req) throws WebAppException{
			Author dataBean=new Author();
		try{
			dataBean.setAuthorId(HtmlUtil.stripTags(req.getParameter("AuthorId") ) );
			dataBean.setFirstName(HtmlUtil.stripTags(req.getParameter("FirstName") ) );
			dataBean.setLastName(HtmlUtil.stripTags(req.getParameter("LastName") ) );
		}catch(Exception e){
			throw new WebAppException(WebAppException.APP_ERROR,e);
}		return dataBean;
	}//end getDataBean

	/************************************
	*Strips tags from strings
	************************************/
	public static Author cleanDataBean(Author dataBean ) {
		dataBean.setFirstName(HtmlUtil.stripTags(dataBean.getFirstName() ) );
		dataBean.setLastName(HtmlUtil.stripTags(dataBean.getLastName() ) );
		return dataBean;
	}//end cleanDataBean


	/************************************
	*Generated method
	*get the correct model class
	*@return model class
	************************************/
	protected AuthorModel getModel() throws WebAppException{
		return JavaWebGenContext.getModel().getAuthorModel();
	}

 //end getModel
//begin action
	/**
	*
	*/
	@RequestMapping("/Author/list.htm")
	public String list(Model uiModel) throws WebAppException {
		List<Author> list =getModel().list();
		uiModel.addAttribute(WebConst.DATA_BEAN_LIST, list);
		return "/admin/AuthorList";
} 
	/**show detail
	*@param result spring result
	*@param uiModel ui model
	* @param req http request
	* @return next action
	* @throws WebAppException web error
	*/
	@RequestMapping("/Author/detail.htm")
	public String detail(@ModelAttribute("author") Author author, BindingResult result, Model uiModel, final HttpServletRequest req ) throws WebAppException {
		Author dataBean =getModel().getById(author.getAuthorId());
		AuthorForm form = new AuthorForm(req);
		form.setData(dataBean);
		uiModel.addAttribute(WebConst.FORM_BEAN,dataBean ); 
		uiModel.addAttribute(WebConst.FORM,form ); 
		return "/admin/AuthorDetail";
	}
	/**create
	* @param result spring result
	* @param uiModel ui model
	* @param req http request
	* @return next action
	* @throws WebAppException web error
	*/
	@RequestMapping("/Author/create.htm")
	public String create(@ModelAttribute("author") Author author, BindingResult result, Model uiModel, final HttpServletRequest req ) throws WebAppException {
		Long id =this.getModel().create(author);
		Author dataBean =getModel().getById(id);
		AuthorForm form = new AuthorForm(req);
		form.setData(dataBean,req);
		uiModel.addAttribute(WebConst.FORM_BEAN,dataBean ); 
		uiModel.addAttribute(WebConst.FORM,form ); 
			return "/admin/AuthorCreate";
	}
	/**create new
	* @param result spring result
	* @param uiModel ui model
	* @param req http request
	* @return next action
	* @throws WebAppException web error
	*/
	@RequestMapping("/Author/newEntity.htm")
	public String newEntity(@ModelAttribute("author") Author author, BindingResult result, Model uiModel, final HttpServletRequest req ) throws WebAppException {
				return "admin/AuthorCreate";
	}
	/** save Form
	* @param result spring result
	* @param uiModel ui model
	* @param req http request
	* @return next action
	* @throws WebAppException web error
	*/
	@RequestMapping("/Author/save.htm")
	public String save(@ModelAttribute("author") Author author, BindingResult result, Model uiModel, final HttpServletRequest req ) throws WebAppException {
		Author dataBean=author;
		AuthorForm form = new AuthorForm(req);
		uiModel.addAttribute(WebConst.FORM_BEAN,dataBean ); 
		uiModel.addAttribute(WebConst.FORM,form ); 
		form.setData(dataBean,req);
		if(form.isValid() ){
			this.getModel().save(dataBean);
			return "redirect:/admin/Author/list.htm";
		}else{
			log.warn("invalid form redisplay");
			return "/admin/AuthorDetail";
 		}
	}
/**delete
	* @param result spring result
	* @param uiModel ui model
	* @param req http request
	* @return next action
	* @throws WebAppException web error
	*/
	@RequestMapping("/Author/delete.htm")
	public String delete(@ModelAttribute("author") Author author, BindingResult result, Model uiModel, final HttpServletRequest req ) throws WebAppException {
		Author dataBean= author;
		this.getModel().remove(dataBean);
		return "redirect:/admin/Author/list.htm";
	}

//end action
}//end impl class
