/*
Copyright (c) 2003-2006 Kevin Scott

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE.
*/
 package org.javaWebGen.data;



/******************************************************************************
* Interface representing the data in one row of the database
* classes that implements this are generally generated by the GeneratDAO object
*
* @author Kevin Scott
*******************************************************************************/
public interface DataBean extends FormBeanAware{

	/**************************************
	*Get row data from Object.  Used by DAO objects
	*@return row data as array of Objects
    *@see org.javaWebGen.data.DAO
	***************************************/
	public Object[] getData();

	/**************************************
	*set object data.  Used by DAO objects
	*@param parms row data
    *@see org.javaWebGen.data.DAO
    *@throws incorrct parms passed
	***************************************/
	public void setData(Object[] parms) throws IllegalArgumentException;

	/**************************************
	*return the type of columns in the database
	*@return array of column types
	***************************************/
	public int[] getDataTypes();
	/**
	 * 
	 * @return
	 */
	//public String getName();
	//public String[] ColNames();





}