/*
Copyright (c) 2018 Kevin Scott
Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ 
package org.javaWebGen.data.bean;

import java.text.*;
import java.math.*;
import java.io.*;
import java.util.ArrayList;
import javax.jdo.annotations.*;
import javax.annotation.Generated;
import org.javaWebGen.exception.DBException;
import org.javaWebGen.data.DbResult;
import org.javaWebGen.data.DataBean;
import org.javaWebGen.data.FormBeanAware;
import org.javaWebGen.util.StringUtil;
import org.json.*;
/******************************************************************************
* WARNING this JTO object is generated by GenerateJDODataBean v2_12 based on Database config
* This class should not be modified, but, may be extended.
* It will be regenerated when the database schema changes.
*******************************************************************************/
@Generated(value = { "org.javaWebGen.generator.GenerateJDODataBean " })
@PersistenceCapable(identityType = IdentityType.APPLICATION)
@SuppressWarnings({ "serial", "unused" }) 
public class Author implements DataBean, Serializable{ 
//begin private Vars
	private static int[] types=null;
	@PrimaryKey
	@Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
	private Long authorId = null;
	@Persistent 
	private String firstName = null;
	@Persistent 
	private String lastName = null;

//begin getters and setters

	/************************************************
	*Get value from bound field author_id
	*@return value from bound data field
	************************************************/
	public Long getAuthorId() {
		return authorId;
	}

	/************************************************
	*Set value to bound field author_id
	*@param value for  bound data field
	************************************************/
	public void setAuthorId(Long value){
		authorId=value;
	}

	/************************************************
	*Get value from bound field first_name
	*@return value from bound data field
	**************************************************/
	public String getFirstName() {
			return firstName;
	}

	/************************************************
	*Set value to bound field first_name
	*@param value for  bound data field
	*************************************************/
	public void setFirstName(String value){
		if(value==null){
			firstName=null;
		}else{
			firstName= value;
		}
	}

	/************************************************
	*Get value from bound field last_name
	*@return value from bound data field
	**************************************************/
	public String getLastName() {
			return lastName;
	}

	/************************************************
	*Set value to bound field last_name
	*@param value for  bound data field
	*************************************************/
	public void setLastName(String value){
		if(value==null){
			lastName=null;
		}else{
			lastName= value;
		}
	}
	/*******************************************************
	*Set a long column author_id based on a string
	*@param input String
	******************************************************/
	public void setAuthorId(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
		authorId=new Long(input);
		}
	}

//begin getData

	/************************************************
	*Get all data Objects bound to data bean  
	*@return data from object as array of objects 
	****************************************************/
	public Object[] getData(){
		Object[] data = new Object[3];
		data[0]=authorId;
		data[1]=firstName;
		data[2]=lastName;
		return data;
	} //end getData

//begin setData

	/*****************************************************************
	*Populates object with data
	*@param data matching the data from a table
	*@see org.javaWebGen.data.DAO
	*@see org.javaWebGen.data.DbResult
	*******************************************************************/
	public void setData(Object[] data) throws IllegalArgumentException{
		if( data.length != 3){
			throw new IllegalArgumentException("query return wrong number of rows "+data.length);
		} //end if

		authorId = (Long) data[0];
		if (data[1]!=null){
			firstName =  data[1].toString();
		}else{
			firstName=null;
		}
		if (data[2]!=null){
			lastName =  data[2].toString();
		}else{
			lastName=null;
		}
	}//end setData

//begin get Insert

	/****************************************************
	*Build SQL insert statement without a where clause 
	*@return sqle  
	*
	*******************************************************/ 
	public static final String getInsertSQL(){
		String sql = "INSERT INTO author (author_id,first_name,last_name) VALUES(?,?,?)";
		return sql;
	}

//begin get update

	/***************************************************
	*Build SQL update statement without a where clause 
	*@return update sql without where clause
	*****************************************************/ 
	public static final String getUpdateSQL(){
		String sql ="UPDATE author SET author_id=? ,first_name=? ,last_name=? ";
		return sql;
	}

//begin get select

	/**************************************************
	*Build SQL select statement without a where clause 
	*@return sqlect SQL without where clause
	*****************************************************/ 
	public static final String getSelectSQL(){
		String sql = "Select author_id,first_name,last_name from author ";
		return sql;
	}

//begin get makeLoad

	/*******************************************************************************************
	*Loads DbResult into object
	*@param result
	*@see org.javaWebGen.data.DbResult
	**********************************************************************************************/ 
	public static ArrayList<Author> load(DbResult result) throws  IllegalArgumentException{
		ArrayList <Author>list= new ArrayList<Author>(result.size() );
		for (int i=0; i< result.size(); i++){
			Author o= new Author();
			o.setData( result.get(i) );
			list.set(i,o);
		 }
		 return list;
	}

//begin make Type 
	/*****************************************************
	*Get an array of column types that match DB table
	*@return array of Types
	******************************************************/
	public int[] getDataTypes(){
		if(types == null){
		 types = new int[3];
			 types[0]=-5;
			 types[1]=12;
			 types[2]=12;
		} //end if
	return types;
	}


//begin toXML()

	/********************************************
	*Builds an XML String based on object data
	*@return XML value of bound data
	***********************************************/
	public String toXML(){
		String xml="<Author authorId=\""+getAuthorId()+"\" firstName=\""+getFirstName()+"\" lastName=\""+getLastName()+"\" />\n";
		return xml;
	}//end toXML()

//make JSON text 

	/*********************************************
	*Builds a JSON String based on object data
	*@return JSON text string
	************************************************/
	public String toJSON() {

		JSONObject jo = new JSONObject();
		try{
			jo.append("authorId",getAuthorId() );
			jo.append("firstName",getFirstName() );
			jo.append("lastName",getLastName() );
			return jo.toString();
 		}catch(JSONException je){
			return " Author{exception:'"+je.getMessage()+"}'";
 		}
	} //end to Json

//  make  Overrides 
	@Override
	/***********************************************
	* Check value of data bound object.   
	*@param object to check value of
	************************************************/
	public boolean equals(Object o){
		if( o!=null && o instanceof FormBeanAware){
			FormBeanAware bean =(FormBeanAware) o;
			return bean.toXML().equals(bean.toXML() );
		}else{
			return false;
		}
	}

}//end Generated class
