/*
Copyright (c) 2012-2013 Kevin Scott
Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ 
package org.javaWebGen.data.bean;

import java.text.*;
import java.math.*;
import java.io.*;
import java.util.ArrayList;
import javax.jdo.annotations.*;
import org.javaWebGen.exception.DBException;
import org.javaWebGen.data.DbResult;
import org.javaWebGen.data.DataBean;
import org.javaWebGen.util.StringUtil;
import org.json.*;
/******************************************************************************
* WARNING this class is generated by GenerateJDODataBean v2_10 based on Database schema
* This class should not be modified, but may be extended.
* It will be regenerated when the database schema changes.
*******************************************************************************/
@PersistenceCapable(identityType = IdentityType.APPLICATION)
@SuppressWarnings({ "serial", "unused" }) //TODO generator should be smarter about this
public class Book implements DataBean, Serializable{ 
//begin private Vars
private static int[] types=null;
@PrimaryKey
@Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
private Long bookId = null;
@Persistent 
private String title = null;
@Persistent 
private String isbn = null;
@Persistent 
private Integer publisherId = null;
@Persistent 
private Integer authorId = null;
@Persistent 
private java.util.Date createDate = null;

//begin getters and setters

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public Long getBookId() {
		return bookId;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setBookId(Long value){
		bookId=value;
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public String getTitle() {
			return title;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setTitle(String value){
		if(value==null){
			title=null;
		}else{
			title= value;
		}
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public String getIsbn() {
			return isbn;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setIsbn(String value){
		if(value==null){
			isbn=null;
		}else{
			isbn= value;
		}
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public int getPublisherId() {
		if(publisherId==null){
			return 0;
		}
		return publisherId.intValue();
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setPublisherId(int value){
		publisherId=new Integer(value);
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public int getAuthorId() {
		if(authorId==null){
			return 0;
		}
		return authorId.intValue();
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setAuthorId(int value){
		authorId=new Integer(value);
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public java.util.Date getCreateDate() {
		return createDate;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setCreateDate(java.util.Date value){
		createDate=value;
	}
	/****************************************
	*set a long column based on a string
	*@param input String
	*******************************************************/
	public void setBookId(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
		bookId=new Long(input);
		}
	}
	/****************************************
	*set a integer column based on a string
	*@param input String
	*******************************************************/
	public void setPublisherId(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
		publisherId=new Integer(input);
		}
	}
	/****************************************
	*set a integer column based on a string
	*@param input String
	*******************************************************/
	public void setAuthorId(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
		authorId=new Integer(input);
		}
	}
	/****************************************
	*set a DATE or TIMESTAMP column based on a string
	*@param input String
	*******************************************************/
	public void setCreateDate(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
			createDate=StringUtil.convertToDate(input);
		}
	}

//begin toXML()

	/************************************
	*Warning Generated method builds an XML String based on object data
	*@return xml 
	****************************************/

	public String toXML(){
		String xml="<Book bookId='"+getBookId()+"' title='"+getTitle()+"' isbn='"+getIsbn()+"' publisherId='"+getPublisherId()+"' authorId='"+getAuthorId()+"' createDate='"+getCreateDate()+"' />\n";
		return xml;
	}//end toXML()
//begin getData

	/****************************************************
	*Warning Generated method gets all data in data bean  
	*@return data from object as array of objects 
	*******************************************************/
	public Object[] getData(){
		Object[] data = new Object[6];
		data[0]=bookId;
		data[1]=title;
		data[2]=isbn;
		data[3]=publisherId;
		data[4]=authorId;
		data[5]=createDate;
		return data;
	} //end getData

//begin setData

	/*********************************************
	*Warning Generated method fills object with data
	*@param data matching the data from a table
	*@see org.javaWebGen.data.DAO
	*@see org.javaWebGen.data.DbResult
	*************************************************/
	public void setData(Object[] data) throws IllegalArgumentException{
		if( data.length != 6){
			throw new IllegalArgumentException("query return wrong number of rows "+data.length);
		} //end if

		bookId = (Long) data[0];
		if (data[1]!=null){
			title =  data[1].toString();
		}else{
			title=null;
		}
		if (data[2]!=null){
			isbn =  data[2].toString();
		}else{
			isbn=null;
		}
		publisherId = (Integer) data[3];
		authorId = (Integer) data[4];
		createDate = (java.util.Date) data[5];
	}//end setData

//begin get Insert

	/********************************************
	*Warning Generated method gets insert statement without a where clause 
	*@return insert statement without where clause  
	************************************************
	*/ 
	public static String getInsertSQL(){
		String sql = "INSERT INTO book (book_id,title,isbn,publisher_id,author_id,create_date) VALUES(?,?,?,?,?,?)";
		return sql;
	}

//begin get update

	/********************************************
	*Warning Generated method gets Update Statement without a where clause
	*@return update sql without where clause
	**************************************/ 
	public static String getUpdateSQL(){
		String sql ="UPDATE book SET book_id=? ,title=? ,isbn=? ,publisher_id=? ,author_id=? ,create_date=? ";
		return sql;
	}

//begin get select

	/************************************
	*Warning Generated method gets a select statement without a where clause
	*@return select sql without a where clause
	****************************************/ 
	public static String getSelectSQL(){
		String sql = "Select book_id,title,isbn,publisher_id,author_id,create_date from book ";
		return sql;
	}

//begin get makeLoad

	/**********************************************
	*Warning Generated method loads DbResult into object
	*@param result
	*@see org.javaWebGen.data.DbResult
	************************************************/ 
	public static ArrayList<Book> load(DbResult result) throws  IllegalArgumentException{
		ArrayList <Book>list= new ArrayList<Book>(result.size() );
		for (int i=0; i< result.size(); i++){
			Book o= new Book();
			o.setData( result.get(i) );
			list.set(i,o);
		 }
		 return list;
	}

//begin make Type 
	/**********************************************
	*get an array of column types that match DB table
	*@return array of Types
	************************************************/
	public int[] getDataTypes(){
		if(types == null){
		 types = new int[6];
			 types[0]=-5;
			 types[1]=12;
			 types[2]=12;
			 types[3]=4;
			 types[4]=4;
			 types[5]=91;
		} //end if
	return types;
	}


//make JSON text 

	/************************************
	*Warning Generated method builds an JSON String based on object data
	*@return JSON text string
	****************************************/

	public String toJSON() {

		JSONObject jo = new JSONObject();
		try{
			jo.append("bookId",getBookId() );
			jo.append("title",getTitle() );
			jo.append("isbn",getIsbn() );
			jo.append("publisherId",getPublisherId() );
			jo.append("authorId",getAuthorId() );
			jo.append("createDate",getCreateDate() );
			return jo.toString();
 		}catch(JSONException je){
			return " Book{exception:'"+je.getMessage()+"}'";
 		}
	} //end to Json

}//end Generated class
