/*
Copyright (c) 2012-2013 Kevin Scott
Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ 
package org.javaWebGen.data.bean;

import java.text.*;
import java.math.*;
import java.io.*;
import java.util.ArrayList;
import javax.jdo.annotations.*;
import org.javaWebGen.exception.DBException;
import org.javaWebGen.data.DbResult;
import org.javaWebGen.data.DataBean;
import org.javaWebGen.util.StringUtil;
import org.json.*;
/******************************************************************************
* WARNING this class is generated by GenerateJDODataBean v2_10 based on Database schema
* This class should not be modified, but may be extended.
* It will be regenerated when the database schema changes.
*******************************************************************************/
@PersistenceCapable(identityType = IdentityType.APPLICATION)
@SuppressWarnings({ "serial", "unused" }) //TODO generator should be smarter about this
public class Location implements DataBean, Serializable{ 
//begin private Vars
private static int[] types=null;
@PrimaryKey
@Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
private Long locationId = null;
@Persistent 
private java.util.Date createDate = null;
@Persistent 
private java.util.Date updateDate = null;
@Persistent 
private String updateBy = null;
@Persistent 
private String comment = null;

//begin getters and setters

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public Long getLocationId() {
		return locationId;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setLocationId(Long value){
		locationId=value;
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public java.util.Date getCreateDate() {
		return createDate;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setCreateDate(java.util.Date value){
		createDate=value;
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public java.util.Date getUpdateDate() {
		return updateDate;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setUpdateDate(java.util.Date value){
		updateDate=value;
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public String getUpdateBy() {
			return updateBy;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setUpdateBy(String value){
		if(value==null){
			updateBy=null;
		}else{
			updateBy= value;
		}
	}

	/********************************************
	*Warning Generated method gets value of field
	*@return value from database column
	***********************************************/
	public String getComment() {
			return comment;
	}

	/*********************************************
	*Warning Generated method sets field value
	*@param value for database column
	*************************************************/
	public void setComment(String value){
		if(value==null){
			comment=null;
		}else{
			comment= value;
		}
	}
	/****************************************
	*set a long column based on a string
	*@param input String
	*******************************************************/
	public void setLocationId(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
		locationId=new Long(input);
		}
	}
	/****************************************
	*set a DATE or TIMESTAMP column based on a string
	*@param input String
	*******************************************************/
	public void setCreateDate(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
			createDate=StringUtil.convertToTime(input);
		}
	}
	/****************************************
	*set a DATE or TIMESTAMP column based on a string
	*@param input String
	*******************************************************/
	public void setUpdateDate(String input) throws ParseException{
		if(input!=null && input.trim().length()>0 ){
			updateDate=StringUtil.convertToTime(input);
		}
	}

//begin toXML()

	/************************************
	*Warning Generated method builds an XML String based on object data
	*@return xml 
	****************************************/

	public String toXML(){
		String xml="<Location locationId='"+getLocationId()+"' createDate='"+getCreateDate()+"' updateDate='"+getUpdateDate()+"' updateBy='"+getUpdateBy()+"' comment='"+getComment()+"' />\n";
		return xml;
	}//end toXML()
//begin getData

	/****************************************************
	*Warning Generated method gets all data in data bean  
	*@return data from object as array of objects 
	*******************************************************/
	public Object[] getData(){
		Object[] data = new Object[5];
		data[0]=locationId;
		data[1]=createDate;
		data[2]=updateDate;
		data[3]=updateBy;
		data[4]=comment;
		return data;
	} //end getData

//begin setData

	/*********************************************
	*Warning Generated method fills object with data
	*@param data matching the data from a table
	*@see org.javaWebGen.data.DAO
	*@see org.javaWebGen.data.DbResult
	*************************************************/
	public void setData(Object[] data) throws IllegalArgumentException{
		if( data.length != 5){
			throw new IllegalArgumentException("query return wrong number of rows "+data.length);
		} //end if

		locationId = (Long) data[0];
		createDate = (java.util.Date) data[1];
		updateDate = (java.util.Date) data[2];
		if (data[3]!=null){
			updateBy =  data[3].toString();
		}else{
			updateBy=null;
		}
		if (data[4]!=null){
			comment =  data[4].toString();
		}else{
			comment=null;
		}
	}//end setData

//begin get Insert

	/********************************************
	*Warning Generated method gets insert statement without a where clause 
	*@return insert statement without where clause  
	************************************************
	*/ 
	public static String getInsertSQL(){
		String sql = "INSERT INTO location (location_id,create_date,update_date,update_by,comment) VALUES(?,?,?,?,?)";
		return sql;
	}

//begin get update

	/********************************************
	*Warning Generated method gets Update Statement without a where clause
	*@return update sql without where clause
	**************************************/ 
	public static String getUpdateSQL(){
		String sql ="UPDATE location SET location_id=? ,create_date=? ,update_date=? ,update_by=? ,comment=? ";
		return sql;
	}

//begin get select

	/************************************
	*Warning Generated method gets a select statement without a where clause
	*@return select sql without a where clause
	****************************************/ 
	public static String getSelectSQL(){
		String sql = "Select location_id,create_date,update_date,update_by,comment from location ";
		return sql;
	}

//begin get makeLoad

	/**********************************************
	*Warning Generated method loads DbResult into object
	*@param result
	*@see org.javaWebGen.data.DbResult
	************************************************/ 
	public static ArrayList<Location> load(DbResult result) throws  IllegalArgumentException{
		ArrayList <Location>list= new ArrayList<Location>(result.size() );
		for (int i=0; i< result.size(); i++){
			Location o= new Location();
			o.setData( result.get(i) );
			list.set(i,o);
		 }
		 return list;
	}

//begin make Type 
	/**********************************************
	*get an array of column types that match DB table
	*@return array of Types
	************************************************/
	public int[] getDataTypes(){
		if(types == null){
		 types = new int[5];
			 types[0]=-5;
			 types[1]=93;
			 types[2]=93;
			 types[3]=12;
			 types[4]=12;
		} //end if
	return types;
	}


//make JSON text 

	/************************************
	*Warning Generated method builds an JSON String based on object data
	*@return JSON text string
	****************************************/

	public String toJSON() {

		JSONObject jo = new JSONObject();
		try{
			jo.append("locationId",getLocationId() );
			jo.append("createDate",getCreateDate() );
			jo.append("updateDate",getUpdateDate() );
			jo.append("updateBy",getUpdateBy() );
			jo.append("comment",getComment() );
			return jo.toString();
 		}catch(JSONException je){
			return " Location{exception:'"+je.getMessage()+"}'";
 		}
	} //end to Json

}//end Generated class
