<%@taglib prefix="t" tagdir="/WEB-INF/tags/admin/" %> 
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<fmt:setBundle basename="messages" var="msg" />
 <t:base> 
   <jsp:attribute name="script"> 
       function deleteClick(dataForm){
	alert('Are you sure you want to delete this record?');
	dataForm.action='/admin/Inventory/delete';
	dataForm.submit();
} //end delete function
function updateClick(dataForm){
	dataForm.action='/admin/Inventory/update';
	dataForm.submit();
} //end update function

  </jsp:attribute>  
  <jsp:attribute name="bodyScript">
     ${form.JQueryScript}
  </jsp:attribute>   
  <jsp:attribute name="title">
     Inventory  </jsp:attribute>   
  <jsp:body>
  <div class='col-m'>	
     <h1>Detail Inventory</h1>
      <div class='row'><a href='/admin/index.jsp'>Admin Menu</a>
<a href='/admin/Inventory/list'>Back to List Menu</a></div>
<form id='dataFormId' name='dataForm' action ='/admin/Inventory/update' METHOD='post'>
<div class='form-group'>
<div class='col-sm-2'>BookId</div><div class='col-sm-10'>${form.bookId.value}</div>
</div>
<input type='hidden' name='bookId' value='${form.bookId.value}'>
<div class='form-group'>
<div class='col-sm-2'>BookId</div><div class='col-sm-10'>${form.bookId.value}</div>
</div>
<input type='hidden' name='bookId' value='${form.bookId.value}'>
${form.locationId.divTag}
<div class='form-group'>
<div class='col-sm-2'>LocationId</div><div class='col-sm-10'>${form.locationId.value}</div>
</div>
<input type='hidden' name='locationId' value='${form.locationId.value}'>
${form.createDate.divTag}
${form.createDate.divTag}
${form.updateDate.divTag}
${form.updateDate.divTag}
${form.updateBy.divTag}
${form.updateBy.divTag}
${form.comment.divTag}
${form.comment.divTag}
<!--update and delete not supported  --></form>

  </div>  </jsp:body>
</t:base>
<!--END DETAIL Page Generated by GenerateView 4_17 -->
