<%@taglib prefix="t" tagdir="/WEB-INF/tags/admin/" %> 
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<fmt:setBundle basename="messages" var="msg" />
 <t:base> 
   <jsp:attribute name="script"> 
       function deleteClick(dataForm){
	alert('Are you sure you want to delete this record?');
	dataForm.action='/admin/Publisher/delete';
	dataForm.submit();
} //end delete function
function updateClick(dataForm){
	dataForm.action='/admin/Publisher/update';
	dataForm.submit();
} //end update function

  </jsp:attribute>  
  <jsp:attribute name="bodyScript">
     ${form.JQueryScript}
  </jsp:attribute>   
  <jsp:attribute name="title">
     Publisher  </jsp:attribute>   
  <jsp:body>
  <div class='col-m'>	
     <h1>Detail Publisher</h1>
      <div class='row'><a href='/admin/index.jsp'>Admin Menu</a>
<a href='/admin/Publisher/list'>Back to List Menu</a></div>
<form id='dataFormId' name='dataForm' action ='/admin/Publisher/update' METHOD='post'>
<div class='form-group'>
<div class='col-sm-2'>PublisherId</div><div class='col-sm-10'>${form.publisherId.value}</div>
</div>
<input type='hidden' name='publisherId' value='${form.publisherId.value}'>
${form.name.divTag}
<button id='button.update' class='btn btn-primary  btn-large' name='updateBut' onClick='updateClick(dataForm)' ><fmt:message key="dialog.save" bundle="${msg}" /></button>
<button id='button.delete' class='btn btn-warning  btn-large' name='deleteBut' onClick='deleteClick(dataForm)'><fmt:message key="dialog.delete" bundle="${msg}" /></button>
</form>

  </div>  </jsp:body>
</t:base>
<!--END DETAIL Page Generated by GenerateView 4_17 -->
