<%@taglib prefix="t" tagdir="/WEB-INF/tags/admin/" %> 
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<fmt:setBundle basename="messages" var="msg" />
 <t:base> 
   <jsp:attribute name="script"> 
       function deleteClick(dataForm){
	alert('Are you sure you want to delete this record?');
	dataForm.action='/admin/Publisher/delete.htm';
	dataForm.submit();
} //end delete function
function updateClick(dataForm){
	dataForm.action='/admin/Publisher/save.htm';
	dataForm.submit();
} //end update function

  </jsp:attribute>  
  <jsp:attribute name="bodyScript">
     ${form.JQueryScript}
  </jsp:attribute>   
  <jsp:attribute name="title">
     Publisher  </jsp:attribute>   
  <jsp:body>
  <div class='col-m'>	
     <h1>Detail Publisher</h1>
      <div class='row'><a href='/admin/index.jsp'>Admin Menu</a>
<a href='/admin/Publisher/list.htm'>Back to List Menu</a></div>
<form id='dataFormId' name='dataForm' action ='/admin/Publisher/save.htm' METHOD='post'>
<!-- primary key -->
<input type='hidden' name='publisherId' value='${form.publisherId.value}'%>
${form.name.divTag}
${form.csrf.divTag}
<button id='button.update' type='submit' class='btn btn-primary  btn-large'><fmt:message key="dialog.add" bundle="${msg}" /></button>
</form>

  </div>  </jsp:body>
</t:base>
<!--END DETAIL Page Generated by GenerateView 4_17 -->
