/*
Copyright (c) 2012 Kevin Scott
Permission is hereby granted, free of charge, to any person obtaining a copy of 
 this software and associated documentation files (the "Software"), to deal in 
 the Software without restriction, including without limitation the rights to 
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
 so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all 
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ 
package org.javaWebGen.test;

import java.util.*;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;
import org.javaWebGen.data.bean.*;
import org.javaWebGen.model.*;
import org.javaWebGen.test.LocalServiceGAETestCase;
/******************************************************************************
* WARNING this class is generated by GenerateTestCase v2_06 based on Database schema     
* This class will <b>NOT</b> be regenerated if the database schema changes. 
* It is only a place holder
* It should be used by adding addition test cases for the business logic
* in the model layer.  It will not test constraints in the data base other
* than the PRIMARY KEY!
*******************************************************************************/
public class AuthorTestCase extends LocalServiceGAETestCase{ 
//begin private Vars

//begin testCRUD()

	/********************************************
	*Warning Generated method runs test on generated CRUD operations 
	************************************************
	*/ 
	@Test 
	public void testCRUD() throws Exception{
		AuthorModel model = new AuthorModel();
		Author bean = new Author();
		Long id=model.create(bean);
		//test by primary key
		Author  entity=model.getById(id);
		Assert.assertTrue("nothing found!",entity!=null); 
		model.save(entity);
		entity=model.getById(id);
		Assert.assertTrue("nothing found!",entity!=null); 
		List<Author> list=model.list();
		Assert.assertTrue("nothing in List!",list.size()>0); 
		model.remove(entity);
	}

	@BeforeClass
	public static void setUpClass() throws Exception {
		createTable();
	}

	private static void createTable() throws Exception{
	}

}//end Generated class
