/*
 Copyright (c) 2014 Kevin Scott All rights  reserved.
 Permission is hereby granted, free of charge, to any person obtaining a copy of 
 this software and associated documentation files (the "Software"), to deal in 
 the Software without restriction, including without limitation the rights to 
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do 
 so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
 SOFTWARE.
 */ package org.javaWebGen.webform;
  
   
 import org.javaWebGen.form.*;
 import javax.servlet.http.HttpServletRequest;

/******************************************************************************
* This class is generated by GenerateWebForm v1_05 based on Database schema     
* This class <b>should</b> be modified.   This class will <b>NOT</b> get
* regenerated and is just generated as a place holder.
* @author Kevin Scott                                                        
* @version $Revision: 1.00 $                                               
*******************************************************************************/
public class LocationForm extends CsrfForm{
 private static final long serialVersionUID = 453453453788212L;
 	/*form fields*/
   	private HtmlNumberField  locationId= new HtmlNumberField("locationId" ,false);
	private HtmlField  createDate= new HtmlDateTimeField("createDate" ,false);
	private HtmlField  updateDate= new HtmlDateTimeField("updateDate" ,false);
	private HtmlField  updateBy= new HtmlTextField("updateBy" ,false);
	private HtmlField  comment= new HtmlTextField("comment" ,false);
 
  /**constructor that builds form*/
 	public LocationForm(HttpServletRequest req){
		super(req);
		this.addField(locationId);
		this.addField(createDate);
		this.addField(updateDate);
		this.addField(updateBy);
		this.addField(comment);
	}
 
 	/** get form name */
	public String getWebFormName(){
 		return "LocationForm";
 	}
 //getters
	public HtmlNumberField getLocationId(){
		 return locationId;
	}
	public HtmlField getCreateDate(){
		 return createDate;
	}
	public HtmlField getUpdateDate(){
		 return updateDate;
	}
	public HtmlField getUpdateBy(){
		 return updateBy;
	}
	public HtmlField getComment(){
		 return comment;
	}
}
 