/*
Copyright (c) 2018 Kevin Scott

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE.
*/

package org.javaWebGen.generator;

import java.io.*;
import java.util.HashMap;

import org.apache.commons.text.StringSubstitutor;
 
import org.javaWebGen.exception.UtilException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated database aware UNIT test objects based on database configuration(torque)XML. 
 * @author Kevin scott
 *
 */
public class GenerateGAETestCase extends TestCaseHelpers {
	 private final static Logger log= LoggerFactory.getLogger(GenerateGAETestCase.class);
     public static final String VERSION="GenerateTestCase v2_06";
     public static final int DEFAULT_PRIMARYKEY_ID=-1;
     public static final String DEFAULT_PRIMARYKEY_VALUE="default";
     private String className=null;

     private String classTemplate=
         "/*\n"+
         "Copyright (c) 2012 Kevin Scott\n"+
         "Permission is hereby granted, free of charge, to any person obtaining a copy of \n"+
        " this software and associated documentation files (the \"Software\"), to deal in \n"+
        " the Software without restriction, including without limitation the rights to \n"+
        " use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies\n"+
         "of the Software, and to permit persons to whom the Software is furnished to do \n"+
        " so, subject to the following conditions:\n"+
        "\n"+
        " The above copyright notice and this permission notice shall be included in all \n"+
        " copies or substantial portions of the Software.\n"+
        "\n"+
        " THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \n"+
         "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \n"+
        " FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE \n"+
        " AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER \n"+
        " LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, \n"+
        " OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE \n"+
        " SOFTWARE.\n "+
        "*/ \n"+
     "package org.javaWebGen.test;\n\n"+

     "import java.util.*;\n"+
     "import org.junit.Assert;\n"+
     "import org.junit.BeforeClass;\n"+
     "import org.junit.Test;\n"+
     "import org.javaWebGen.data.bean.*;\n"+
     "import org.javaWebGen.model.*;\n"+
     "import org.javaWebGen.test.LocalServiceGAETestCase;\n"+
 
//     "import junit.framework.TestCase;\n"+
      "/******************************************************************************\n"+
      "* WARNING this class is generated by "+VERSION+" based on Database schema     \n"+
      "* This class will <b>NOT</b> be regenerated if the database schema changes. \n"+
      "* It is only a place holder\n" +
      "* It should be used by adding addition test cases for the business logic\n"+
      "* in the model layer.  It will not test constraints in the data base other\n"+
      "* than the PRIMARY KEY!\n"+
      "*******************************************************************************/\n"+
      "public class ${javaWebGen.className} extends LocalServiceGAETestCase{ \n"+
      "//begin private Vars\n"+
      "${javaWebGen.vars}\n"+
      "//begin testCRUD()\n"+
      "${javaWebGen.crud}\n"+
      "${javaWebGen.create}\n"+
     "}//end Generated class\n";
     
     private String localServiceTemplate=
    	"package org.javaWebGen.test;\r\n" + 
    	"\r\n" + 
    	"\r\n" + 
    	"import org.javaWebGen.util.LocalTestaware;\r\n" + 
    	"\r\n" + 
    	"import org.junit.After;\r\n" + 
    	"import org.junit.Before;\r\n" + 
    	"\r\n" + 
    	"import com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig;\r\n" + 
    	"import com.google.appengine.tools.development.testing.LocalServiceTestHelper;\r\n" + 
    	"\r\n" + 
    	"/*\r\n" + 
    	" * import com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig;\r\n" + 
    	"import com.google.appengine.tools.development.testing.LocalServiceTestHelper;*/\r\n" + 
    	"\r\n" + 
    	"	public class LocalServiceGAETestCase implements LocalTestaware{\r\n" + 
    	"		 private final LocalServiceTestHelper helper =  \r\n" + 
    	"		            new LocalServiceTestHelper(new LocalDatastoreServiceTestConfig()); \r\n" + 
    	"\r\n" + 
    	"	    @Before\r\n" + 
    	"	    public void setUp()  {     \r\n" + 
    	"	    	\r\n" + 
    	"	    	helper.setUp();\r\n" + 
    	"	    	log(\"setUp\");\r\n" + 
    	"	    }\r\n" + 
    	"\r\n" + 
    	"	    @After\r\n" + 
    	"	    public void tearDown() {\r\n" + 
    	"	    	\r\n" + 
    	"	        // not strictly necessary to null these out but there's no harm either\r\n" + 
    	"	    	helper.tearDown();\r\n" + 
    	"	    	log(\"tearDown\");\r\n" + 
    	"\r\n" + 
    	"	    }\r\n" + 
    	"		public void log(String msg){\r\n" + 
    	"			System.out.println(msg);\r\n" + 
    	"		}\r\n" + 
    	"	}\r\n" + 
    	"\n";


/**
 * make test Insert TestCase
 * @param cols
 * @param types
 * @return text
 * @throws Exception 
 */
    public String makeCRUD(String[] cols,int[] types) throws Exception{
    	String modelName=DataMapper.formatClassName(getTableName() )+"Model";
    	String beanName=DataMapper.formatClassName(getTableName() )+"";
    	int[] keyTypes=this.getPrimaryKeyTypes();
    	String javaType=DataMapper.getJavaTypeFromSQLType(keyTypes[0]);
    	
    	String findByKey="\t\t"+javaType+" id=model.create(bean);\n";
    	if(keyTypes.length==1){ //only if one primary key
    		findByKey+=
    		"\t\t//test by primary key\n"+		
            "\t\t"+beanName+"  entity=model.getById(id);\n"+
            "\t\tAssert.assertTrue(\"nothing found!\",entity!=null); \n"+
            "\t\tmodel.save(entity);\n"+
    		 "\t\tentity=model.getById(id);\n"+
    		 "\t\tAssert.assertTrue(\"nothing found!\",entity!=null); \n";
    	}else{
    		findByKey+=
    	            "\t\t//can only handle one primary key you will need to write a manual testcase!";
    	}
    	String text=
        "\n\t/********************************************\n"+
        "\t*Warning Generated method runs test on generated CRUD operations \n"+       
        "\t************************************************\n"+
        "\t*/ \n"+
        "\t@Test \n"+
        "\tpublic void testCRUD() throws Exception{\n"+
        "\t\t"+modelName+" model = new "+modelName+"();\n"+
        "\t\t"+beanName+" bean = new "+beanName+"();\n"+ 
        findByKey+
        "\t\tList<"+beanName+"> list=model.list();\n"+
        "\t\tAssert.assertTrue(\"nothing in List!\",list.size()>0); \n"+
        "\t\tmodel.remove(entity);\n"+
        "\t}\n";       
        return text;
    }


/**
 * make test Insert TestCase
 * @param cols names
 * @param types col types
 * @return text from table
 * @throws Exception 
 */
    public String makeTable(String[] cols,int[] types) throws Exception{
    	//String modelName=DataMapper.formatClassName(getTableName() )+"Model";
    	//String beanName=DataMapper.formatClassName(getTableName() )+"";
    	//int[] keyTypes=this.getPrimaryKeyTypes();
    	//ArrayList<String> primaryKeys=this.getPrimaryKeys();
    	//String javaType=DataMapper.getJavaTypeFromSQLType(keyTypes[0]);
    	/*String sql="\"CREATE TABLE "+getTableName()+" (";
    	boolean isFirst=true;
    	for(int i=0;i<cols.length;i++){
    		if(isFirst){
    			isFirst=false;
    		}else{
    			sql+=",";
    		}
    		sql+=cols[i]+ " "+this.getSqlTypeMap().get(cols[i]);
    		if(this.getSizeMap().get(cols[i])!=null){
    			sql+="("+this.getSizeMap().get(cols[i])+")";
    		}
    		boolean isKey=false;
    		for (String keyName:primaryKeys){
    			if(keyName.equals(cols[i])){
    				isKey=true;
    			}
    		}
    		if(isKey){
    			sql+=" NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) ";
    		} 

    	
    	}
    	sql+=")\";\n";*/
    	String text=""
    	 + "\t@BeforeClass\n"
    	 + "\tpublic static void setUpClass() throws Exception {\n"
//    	 + "\t\tTestJndiSetup.doSetup(\"testDB\");\n"
    	 + "\t\tcreateTable();\n"
    	 + "\t}\n\n"
       	 + "\tprivate static void createTable() throws Exception{\n"
 
      //	+  "\t  } \n"
    	 + "\t}\n";
        return text;
    }
    /************************************************8**
    *build class based on template
    ********************************************************/
    protected String buldClass() throws Exception{
    	String[] colNames=getColNames();
    	int[] colTypes=getColTypes();
    	//String tableName = getTableName();
    	
        if( colNames!=null &&  colTypes !=null){
            String crud = makeCRUD(colNames, colTypes);
            /*String[] parm = new String[7];
            parm[0]= className;       
            parm[1]="";
            parm[2]=crud;*/
            HashMap<String,String> valueMap = new HashMap<String,String>();
            valueMap.put("javaWebGen.className", className);
            valueMap.put("javaWebGen.vars", "");
            valueMap.put("javaWebGen.crud", crud);
            valueMap.put("javaWebGen.create", this.makeTable(colNames, colTypes) ) ;
            StringSubstitutor sub= new StringSubstitutor(valueMap);
            //String classText = this.getClassText(classTemplate,parm);
            return sub.replace(classTemplate);
        }else{
            return "";
        }
        
    }

/**
 * main writing loop called by processFile
 */
    protected void execute() throws UtilException{
    	
        try {
        	className=DataMapper.formatClassName(getTableName() )+"TestCase";
        	
			writeJavaClass(buldClass() );
		} catch (Exception e) {
			throw new UtilException(UtilException.CODE_GENERATOR_EXEC,e);
		}
    }
    
    /**
     * process stuff after main execute loop has finished 
     * processing tables
     * @throws FileNotFoundException 
     */
    @Override
    protected void postExecute() throws UtilException {
    	super.postExecute();
    	log.debug("postExecute()>");
        String fileName=getFilePath()+File.separator+"LocalServiceGAETestCase"+".java";
        File file = new File(fileName);
       if(!file.exists() ){  //only write if file does not exist
    	   try {
        //if(true){  //only write if file does not exist
        	PrintWriter out = new PrintWriter(file);
	        out.print(localServiceTemplate);
	        out.flush();
	        out.close();
    	   }catch(IOException e) {
    		   throw new UtilException(UtilException.CODE_GENERATOR_EXEC,e);
    	   }
	        log.info("---Write TestCase "+fileName);
        } 
     /* fileName=getFilePath()+File.separator+"MockRequestTestCase"+".java";
      file = new File(fileName);
      if(!file.exists() ){  //only write if file does not exist
   	   try {
       //if(true){  //only write if file does not exist
       	PrintWriter out = new PrintWriter(file);
	        out.print(this.mockRequest);
	        out.flush();
	        out.close();
   	   }catch(IOException e) {
   		   throw new UtilException(UtilException.CODE_GENERATOR_EXEC,e);
   	   }
	        log.info("---Write TestCase "+className);
       }
       */ 
 
      log.debug("<postExecute()");
    }
    /**
    *Write out generated class
    *
    *@param text
    */
    private void writeJavaClass(String text) throws IOException{
    	//String tableName=getTableName();
	    	
        String fileName=getFilePath()+File.separator+className+".java";
        File file = new File(fileName);
       if(!file.exists() && getPrimaryKeys().size() >0 ){  //only write if file does not exist
        //if(true){  //only write if file does not exist
        	PrintWriter out = new PrintWriter(file);
	        out.print(text);
	        out.flush();
	        out.close();
	        
	        log.info("---Write TestCase "+className);
        }

    }

	/**
    * main
    */
    public static void main(String[] args) {
        try{ 	
        	GenerateGAETestCase app = new GenerateGAETestCase();
        	app.setCmdParms(args);
        	app.init();
            app.processXmlFile(app.getFileName());
       	}catch(Exception e){
       		log.error("main error",e);
       		System.exit(911);
       	}
    }
    /**********************************************************
     *generate a string to convert from a string to correct
     *Object type
     *@param primaryKey
     *@param SQL type
     *@return text for generated class
     **********************************************************/
    /* private String getVarDeclaration(String key, int type) {
         	String text="";
         	String name=DataMapper.formatVarName(key.toString() );
         	
         	Util.debug("pkey="+name +"|type="+type);
             switch (type){
                 case Types.CHAR:
                 case Types.VARCHAR:
                 case Types.LONGVARCHAR:
                 	text+="String "+name+"= \""+DEFAULT_PRIMARYKEY_VALUE+"\";\n"; 
                     break;
                 case Types.DATE:
                 case Types.TIMESTAMP:
                  	text+="java.util.Date "+name+"= new java.util.Date();//use current Date\n"; 
                     break;
                 case Types.BIT:
                 case Types.BOOLEAN:
                	 text+="boolean "+name+"= false;\n";
                	 break;
                 case Types.TINYINT:
                	 text+="byte "+name+"= 0;\n";
                	 break;
                	 
                 case Types.SMALLINT:
                	 text+="short "+name+"= -1;\n";
                	 break;
                	 
                 case Types.INTEGER:
                 	text+="int "+name+"= -1;\n"; 
                 break;
                 case Types.BIGINT:    
                 	text+="long "+name+" = -1L;\n"; 
                 	break;
                 case Types.REAL:    
                  	text+="float "+name+" = -1.0F;\n"; 
                  	break;
                 
                 case Types.FLOAT:
                 case Types.DOUBLE:
                  	text+="double "+name+" = -1.0;\n"; 
                 	break;
                 case Types.NUMERIC:
                 case Types.DECIMAL:
                 	text+="BigDecimal "+name+"= new BigDecimal(\"-1.00\");\n"; 
                     break;
                 case Types.LONGVARBINARY:
                 case Types.BINARY:    
                 case Types.BLOB:  
                 case Types.JAVA_OBJECT :  
                 case Types.CLOB : 
                 case Types.OTHER :
                     Util.warn("can not use a BLOB as a key=");
                     break;
             }//end switch                
             
         return text;
     }*/
     /**
      * need to set primary keys to something
      * @param type
      * @return
      */
     /*private String getDefaultValues(String key,int type){
         String text="";
    	 switch (type){
         
	         
	         case Types.CHAR:
	         case Types.VARCHAR:
	         case Types.LONGVARCHAR:
	
	        	 text+="bean.set"+DataMapper.formatClassName(key)+"("+DataMapper.formatVarName(key)+");\n";
	         break;
	         case Types.DATE:
	         case Types.TIMESTAMP:
	        	 text+="bean.set"+DataMapper.formatClassName(key)+"("+DataMapper.formatVarName(key)+");\n";   
	         break;
	         case Types.BIT:
	         case Types.TINYINT:
	         case Types.SMALLINT:
	         case Types.INTEGER:
	         case Types.BIGINT:    
	         case Types.FLOAT:
	         case Types.DOUBLE:
	         case Types.DECIMAL:
	        	 text+="bean.set"+DataMapper.formatClassName(key)+"("+DataMapper.formatVarName(key)+");\n";   
	        	
	         break;
    	 }
    	 return text;
     }*/
/**
 * 
 */
	public void useage() {
        System.out.println("To Process all tables in a text file");
        System.out.println("USAGE GenerateTestCase -f <filename> <path>");
        System.exit(1);
	}

@Override
public void init() throws UtilException {
	// noop
	
}

}